version: '3'
services:
  neovim:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        - DOCKER_BUILDKIT=1
    volumes:
      - ./workspace:/root/workspace
    tty: true
    stdin_open: true
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}

